-- Seed Top 10 category clinics (Nahal #1 + samples)
-- Generated for scripts/seed-category-top10-docker.sh
BEGIN;
CREATE TABLE IF NOT EXISTS category_top_clinics (
  id TEXT PRIMARY KEY,
  category_id TEXT NOT NULL,
  clinic_id INTEGER NOT NULL,
  rank INTEGER NOT NULL,
  name TEXT,
  tagline TEXT,
  image TEXT,
  link TEXT,
  badge TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  clicks INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_category_top_cat ON category_top_clinics (category_id, rank);
DELETE FROM category_top_clinics WHERE category_id = 'hair';
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r1-seed', 'hair', 114, 1, 'کلینیک نهال', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'clinics/114/Hero.webp', 'profile.html?id=114', 'ویژه', 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r2-seed', 'hair', 101, 2, 'Shiraz Sample Clinic 1', 'کلینیک تخصصی پوست و مو', 'images/toranj.webp', 'profile.html?id=101', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r3-seed', 'hair', 104, 3, 'Shiraz Sample Clinic 4', 'کلینیک زیبایی و کاشت مو', 'images/rokh.webp', 'profile.html?id=104', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r4-seed', 'hair', 105, 4, 'Shiraz Sample Clinic 5', 'کلینیک زیبایی و کاشت مو', 'images/motaqi.webp', 'profile.html?id=105', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r5-seed', 'hair', 115, 5, 'Shiraz Sample Clinic 14', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/clinic-saleh.png', 'profile.html?id=115', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r6-seed', 'hair', 106, 6, 'Shiraz Sample Clinic 6', 'کلینیک فوق تخصصی کاشت مو', 'images/shiraz-transplant.webp', 'profile.html?id=106', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r7-seed', 'hair', 107, 7, 'Shiraz Sample Clinic 7', 'کلینیک تخصصی لیزر', 'images/shiraz-laser.webp', 'profile.html?id=107', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r8-seed', 'hair', 108, 8, 'Shiraz Sample Clinic 8', 'کلینیک پوست و زیبایی', 'images/sibsorkh.webp', 'profile.html?id=108', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r9-seed', 'hair', 112, 9, 'Shiraz Sample Clinic 12', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/armani.webp', 'profile.html?id=112', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-hair-r10-seed', 'hair', 103, 10, 'Shiraz Sample Clinic 3', 'کلینیک تخصصی پوست،مو،زیبایی و لیزر', 'images/sample-clinic-services.png', 'profile.html?id=103', NULL, 1, 0, datetime('now'));
DELETE FROM category_top_clinics WHERE category_id = 'skin';
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r1-seed', 'skin', 114, 1, 'کلینیک نهال', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'clinics/114/Hero.webp', 'profile.html?id=114', 'ویژه', 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r2-seed', 'skin', 101, 2, 'Shiraz Sample Clinic 1', 'کلینیک تخصصی پوست و مو', 'images/toranj.webp', 'profile.html?id=101', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r3-seed', 'skin', 104, 3, 'Shiraz Sample Clinic 4', 'کلینیک زیبایی و کاشت مو', 'images/rokh.webp', 'profile.html?id=104', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r4-seed', 'skin', 105, 4, 'Shiraz Sample Clinic 5', 'کلینیک زیبایی و کاشت مو', 'images/motaqi.webp', 'profile.html?id=105', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r5-seed', 'skin', 115, 5, 'Shiraz Sample Clinic 14', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/clinic-saleh.png', 'profile.html?id=115', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r6-seed', 'skin', 106, 6, 'Shiraz Sample Clinic 6', 'کلینیک فوق تخصصی کاشت مو', 'images/shiraz-transplant.webp', 'profile.html?id=106', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r7-seed', 'skin', 107, 7, 'Shiraz Sample Clinic 7', 'کلینیک تخصصی لیزر', 'images/shiraz-laser.webp', 'profile.html?id=107', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r8-seed', 'skin', 108, 8, 'Shiraz Sample Clinic 8', 'کلینیک پوست و زیبایی', 'images/sibsorkh.webp', 'profile.html?id=108', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r9-seed', 'skin', 112, 9, 'Shiraz Sample Clinic 12', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/armani.webp', 'profile.html?id=112', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-skin-r10-seed', 'skin', 103, 10, 'Shiraz Sample Clinic 3', 'کلینیک تخصصی پوست،مو،زیبایی و لیزر', 'images/sample-clinic-services.png', 'profile.html?id=103', NULL, 1, 0, datetime('now'));
DELETE FROM category_top_clinics WHERE category_id = 'laser';
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r1-seed', 'laser', 114, 1, 'کلینیک نهال', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'clinics/114/Hero.webp', 'profile.html?id=114', 'ویژه', 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r2-seed', 'laser', 101, 2, 'Shiraz Sample Clinic 1', 'کلینیک تخصصی پوست و مو', 'images/toranj.webp', 'profile.html?id=101', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r3-seed', 'laser', 104, 3, 'Shiraz Sample Clinic 4', 'کلینیک زیبایی و کاشت مو', 'images/rokh.webp', 'profile.html?id=104', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r4-seed', 'laser', 105, 4, 'Shiraz Sample Clinic 5', 'کلینیک زیبایی و کاشت مو', 'images/motaqi.webp', 'profile.html?id=105', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r5-seed', 'laser', 115, 5, 'Shiraz Sample Clinic 14', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/clinic-saleh.png', 'profile.html?id=115', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r6-seed', 'laser', 106, 6, 'Shiraz Sample Clinic 6', 'کلینیک فوق تخصصی کاشت مو', 'images/shiraz-transplant.webp', 'profile.html?id=106', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r7-seed', 'laser', 107, 7, 'Shiraz Sample Clinic 7', 'کلینیک تخصصی لیزر', 'images/shiraz-laser.webp', 'profile.html?id=107', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r8-seed', 'laser', 108, 8, 'Shiraz Sample Clinic 8', 'کلینیک پوست و زیبایی', 'images/sibsorkh.webp', 'profile.html?id=108', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r9-seed', 'laser', 112, 9, 'Shiraz Sample Clinic 12', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/armani.webp', 'profile.html?id=112', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-laser-r10-seed', 'laser', 103, 10, 'Shiraz Sample Clinic 3', 'کلینیک تخصصی پوست،مو،زیبایی و لیزر', 'images/sample-clinic-services.png', 'profile.html?id=103', NULL, 1, 0, datetime('now'));
DELETE FROM category_top_clinics WHERE category_id = 'injection';
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r1-seed', 'injection', 114, 1, 'کلینیک نهال', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'clinics/114/Hero.webp', 'profile.html?id=114', 'ویژه', 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r2-seed', 'injection', 101, 2, 'Shiraz Sample Clinic 1', 'کلینیک تخصصی پوست و مو', 'images/toranj.webp', 'profile.html?id=101', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r3-seed', 'injection', 104, 3, 'Shiraz Sample Clinic 4', 'کلینیک زیبایی و کاشت مو', 'images/rokh.webp', 'profile.html?id=104', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r4-seed', 'injection', 105, 4, 'Shiraz Sample Clinic 5', 'کلینیک زیبایی و کاشت مو', 'images/motaqi.webp', 'profile.html?id=105', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r5-seed', 'injection', 115, 5, 'Shiraz Sample Clinic 14', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/clinic-saleh.png', 'profile.html?id=115', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r6-seed', 'injection', 106, 6, 'Shiraz Sample Clinic 6', 'کلینیک فوق تخصصی کاشت مو', 'images/shiraz-transplant.webp', 'profile.html?id=106', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r7-seed', 'injection', 107, 7, 'Shiraz Sample Clinic 7', 'کلینیک تخصصی لیزر', 'images/shiraz-laser.webp', 'profile.html?id=107', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r8-seed', 'injection', 108, 8, 'Shiraz Sample Clinic 8', 'کلینیک پوست و زیبایی', 'images/sibsorkh.webp', 'profile.html?id=108', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r9-seed', 'injection', 112, 9, 'Shiraz Sample Clinic 12', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/armani.webp', 'profile.html?id=112', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-injection-r10-seed', 'injection', 103, 10, 'Shiraz Sample Clinic 3', 'کلینیک تخصصی پوست،مو،زیبایی و لیزر', 'images/sample-clinic-services.png', 'profile.html?id=103', NULL, 1, 0, datetime('now'));
DELETE FROM category_top_clinics WHERE category_id = 'surgery';
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r1-seed', 'surgery', 114, 1, 'کلینیک نهال', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'clinics/114/Hero.webp', 'profile.html?id=114', 'ویژه', 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r2-seed', 'surgery', 101, 2, 'Shiraz Sample Clinic 1', 'کلینیک تخصصی پوست و مو', 'images/toranj.webp', 'profile.html?id=101', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r3-seed', 'surgery', 104, 3, 'Shiraz Sample Clinic 4', 'کلینیک زیبایی و کاشت مو', 'images/rokh.webp', 'profile.html?id=104', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r4-seed', 'surgery', 105, 4, 'Shiraz Sample Clinic 5', 'کلینیک زیبایی و کاشت مو', 'images/motaqi.webp', 'profile.html?id=105', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r5-seed', 'surgery', 115, 5, 'Shiraz Sample Clinic 14', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/clinic-saleh.png', 'profile.html?id=115', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r6-seed', 'surgery', 106, 6, 'Shiraz Sample Clinic 6', 'کلینیک فوق تخصصی کاشت مو', 'images/shiraz-transplant.webp', 'profile.html?id=106', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r7-seed', 'surgery', 107, 7, 'Shiraz Sample Clinic 7', 'کلینیک تخصصی لیزر', 'images/shiraz-laser.webp', 'profile.html?id=107', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r8-seed', 'surgery', 108, 8, 'Shiraz Sample Clinic 8', 'کلینیک پوست و زیبایی', 'images/sibsorkh.webp', 'profile.html?id=108', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r9-seed', 'surgery', 112, 9, 'Shiraz Sample Clinic 12', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/armani.webp', 'profile.html?id=112', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-surgery-r10-seed', 'surgery', 103, 10, 'Shiraz Sample Clinic 3', 'کلینیک تخصصی پوست،مو،زیبایی و لیزر', 'images/sample-clinic-services.png', 'profile.html?id=103', NULL, 1, 0, datetime('now'));
DELETE FROM category_top_clinics WHERE category_id = 'slimming';
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r1-seed', 'slimming', 114, 1, 'کلینیک نهال', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'clinics/114/Hero.webp', 'profile.html?id=114', 'ویژه', 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r2-seed', 'slimming', 101, 2, 'Shiraz Sample Clinic 1', 'کلینیک تخصصی پوست و مو', 'images/toranj.webp', 'profile.html?id=101', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r3-seed', 'slimming', 104, 3, 'Shiraz Sample Clinic 4', 'کلینیک زیبایی و کاشت مو', 'images/rokh.webp', 'profile.html?id=104', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r4-seed', 'slimming', 105, 4, 'Shiraz Sample Clinic 5', 'کلینیک زیبایی و کاشت مو', 'images/motaqi.webp', 'profile.html?id=105', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r5-seed', 'slimming', 115, 5, 'Shiraz Sample Clinic 14', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/clinic-saleh.png', 'profile.html?id=115', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r6-seed', 'slimming', 106, 6, 'Shiraz Sample Clinic 6', 'کلینیک فوق تخصصی کاشت مو', 'images/shiraz-transplant.webp', 'profile.html?id=106', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r7-seed', 'slimming', 107, 7, 'Shiraz Sample Clinic 7', 'کلینیک تخصصی لیزر', 'images/shiraz-laser.webp', 'profile.html?id=107', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r8-seed', 'slimming', 108, 8, 'Shiraz Sample Clinic 8', 'کلینیک پوست و زیبایی', 'images/sibsorkh.webp', 'profile.html?id=108', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r9-seed', 'slimming', 112, 9, 'Shiraz Sample Clinic 12', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/armani.webp', 'profile.html?id=112', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-slimming-r10-seed', 'slimming', 103, 10, 'Shiraz Sample Clinic 3', 'کلینیک تخصصی پوست،مو،زیبایی و لیزر', 'images/sample-clinic-services.png', 'profile.html?id=103', NULL, 1, 0, datetime('now'));
DELETE FROM category_top_clinics WHERE category_id = 'lasik';
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r1-seed', 'lasik', 114, 1, 'کلینیک نهال', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'clinics/114/Hero.webp', 'profile.html?id=114', 'ویژه', 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r2-seed', 'lasik', 101, 2, 'Shiraz Sample Clinic 1', 'کلینیک تخصصی پوست و مو', 'images/toranj.webp', 'profile.html?id=101', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r3-seed', 'lasik', 104, 3, 'Shiraz Sample Clinic 4', 'کلینیک زیبایی و کاشت مو', 'images/rokh.webp', 'profile.html?id=104', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r4-seed', 'lasik', 105, 4, 'Shiraz Sample Clinic 5', 'کلینیک زیبایی و کاشت مو', 'images/motaqi.webp', 'profile.html?id=105', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r5-seed', 'lasik', 115, 5, 'Shiraz Sample Clinic 14', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/clinic-saleh.png', 'profile.html?id=115', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r6-seed', 'lasik', 106, 6, 'Shiraz Sample Clinic 6', 'کلینیک فوق تخصصی کاشت مو', 'images/shiraz-transplant.webp', 'profile.html?id=106', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r7-seed', 'lasik', 107, 7, 'Shiraz Sample Clinic 7', 'کلینیک تخصصی لیزر', 'images/shiraz-laser.webp', 'profile.html?id=107', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r8-seed', 'lasik', 108, 8, 'Shiraz Sample Clinic 8', 'کلینیک پوست و زیبایی', 'images/sibsorkh.webp', 'profile.html?id=108', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r9-seed', 'lasik', 112, 9, 'Shiraz Sample Clinic 12', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/armani.webp', 'profile.html?id=112', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-lasik-r10-seed', 'lasik', 103, 10, 'Shiraz Sample Clinic 3', 'کلینیک تخصصی پوست،مو،زیبایی و لیزر', 'images/sample-clinic-services.png', 'profile.html?id=103', NULL, 1, 0, datetime('now'));
DELETE FROM category_top_clinics WHERE category_id = 'femto-lasik';
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r1-seed', 'femto-lasik', 114, 1, 'کلینیک نهال', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'clinics/114/Hero.webp', 'profile.html?id=114', 'ویژه', 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r2-seed', 'femto-lasik', 101, 2, 'Shiraz Sample Clinic 1', 'کلینیک تخصصی پوست و مو', 'images/toranj.webp', 'profile.html?id=101', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r3-seed', 'femto-lasik', 104, 3, 'Shiraz Sample Clinic 4', 'کلینیک زیبایی و کاشت مو', 'images/rokh.webp', 'profile.html?id=104', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r4-seed', 'femto-lasik', 105, 4, 'Shiraz Sample Clinic 5', 'کلینیک زیبایی و کاشت مو', 'images/motaqi.webp', 'profile.html?id=105', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r5-seed', 'femto-lasik', 115, 5, 'Shiraz Sample Clinic 14', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/clinic-saleh.png', 'profile.html?id=115', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r6-seed', 'femto-lasik', 106, 6, 'Shiraz Sample Clinic 6', 'کلینیک فوق تخصصی کاشت مو', 'images/shiraz-transplant.webp', 'profile.html?id=106', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r7-seed', 'femto-lasik', 107, 7, 'Shiraz Sample Clinic 7', 'کلینیک تخصصی لیزر', 'images/shiraz-laser.webp', 'profile.html?id=107', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r8-seed', 'femto-lasik', 108, 8, 'Shiraz Sample Clinic 8', 'کلینیک پوست و زیبایی', 'images/sibsorkh.webp', 'profile.html?id=108', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r9-seed', 'femto-lasik', 112, 9, 'Shiraz Sample Clinic 12', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/armani.webp', 'profile.html?id=112', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-femto-lasik-r10-seed', 'femto-lasik', 103, 10, 'Shiraz Sample Clinic 3', 'کلینیک تخصصی پوست،مو،زیبایی و لیزر', 'images/sample-clinic-services.png', 'profile.html?id=103', NULL, 1, 0, datetime('now'));
DELETE FROM category_top_clinics WHERE category_id = 'prk';
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r1-seed', 'prk', 114, 1, 'کلینیک نهال', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'clinics/114/Hero.webp', 'profile.html?id=114', 'ویژه', 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r2-seed', 'prk', 101, 2, 'Shiraz Sample Clinic 1', 'کلینیک تخصصی پوست و مو', 'images/toranj.webp', 'profile.html?id=101', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r3-seed', 'prk', 104, 3, 'Shiraz Sample Clinic 4', 'کلینیک زیبایی و کاشت مو', 'images/rokh.webp', 'profile.html?id=104', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r4-seed', 'prk', 105, 4, 'Shiraz Sample Clinic 5', 'کلینیک زیبایی و کاشت مو', 'images/motaqi.webp', 'profile.html?id=105', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r5-seed', 'prk', 115, 5, 'Shiraz Sample Clinic 14', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/clinic-saleh.png', 'profile.html?id=115', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r6-seed', 'prk', 106, 6, 'Shiraz Sample Clinic 6', 'کلینیک فوق تخصصی کاشت مو', 'images/shiraz-transplant.webp', 'profile.html?id=106', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r7-seed', 'prk', 107, 7, 'Shiraz Sample Clinic 7', 'کلینیک تخصصی لیزر', 'images/shiraz-laser.webp', 'profile.html?id=107', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r8-seed', 'prk', 108, 8, 'Shiraz Sample Clinic 8', 'کلینیک پوست و زیبایی', 'images/sibsorkh.webp', 'profile.html?id=108', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r9-seed', 'prk', 112, 9, 'Shiraz Sample Clinic 12', 'کلینیک کاشت مو،پوست،لیزر و زیبایی', 'images/armani.webp', 'profile.html?id=112', NULL, 1, 0, datetime('now'));
INSERT INTO category_top_clinics (id, category_id, clinic_id, rank, name, tagline, image, link, badge, active, clicks, created_at) VALUES ('cat-prk-r10-seed', 'prk', 103, 10, 'Shiraz Sample Clinic 3', 'کلینیک تخصصی پوست،مو،زیبایی و لیزر', 'images/sample-clinic-services.png', 'profile.html?id=103', NULL, 1, 0, datetime('now'));
COMMIT;
SELECT category_id, COUNT(*) AS n FROM category_top_clinics GROUP BY category_id ORDER BY category_id;
